ProsjektNosted/Controllers/FAQController.cs
using Microsoft.AspNetCore.Mvc;

namespace Prosjekt.Controllers
{
    public class FAQController : Controller
    {
        // viser FAQ
        public IActionResult FAQ()
        {
            return View();
        }
    }
}

ProsjektNosted/Controllers/KontaktController.cs
using Microsoft.AspNetCore.Mvc;
using Prosjekt.Models;
using System.Net;
using System.Net.Http;
using System.Net.Mail;

namespace Prosjekt.Controllers
{
    public class KontaktController : Controller
    {
        public IActionResult KontaktOss()
        {
            return View();
        }

        // Funskjon vil gi bruker resposen om det var vellykke eller ikke
        // ved innsending av form
        [HttpPost]
        public IActionResult SumbitKontaktForm(KontaktFormModel kontaktForm)
        {
            if (!ModelState.IsValid) return View("KontaktOss");

            try
            {
                //Hentet fra https://stackoverflow.com/questions/17962784/using-mailmessage-to-send-emails-in-c-sharp
                MailMessage mail = new MailMessage();

                //mail addressen den sender fra
                mail.From = new MailAddress("gruppe9Uia@outlook.com");

                //Emnet til mailen
                mail.Subject = "Kontakt form";

                //innholdet i mail
                mail.Body = $"Hei {kontaktForm.navn}\nTusen takk at du sendt din meldin. Vi vil kontakt deg snartest som mulig\n Hilsen Gruppe 9";
                mail.IsBodyHtml = true;

                //mottaker
                mail.To.Add(kontaktForm.email);
                //Passord UiaProsjekt
                //Email gruppe9Uia@gmail.com
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.office365.com";
                smtp.Port = 587;
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new NetworkCredential("gruppe9Uia@outlook.com", "UiaProsjekt");
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.EnableSsl = true;

                //hentet fra https://stackoverflow.com/questions/2859790/the-request-was-aborted-could-not-create-ssl-tls-secure-channel
                ServicePointManager.Expect100Continue = true;
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
                smtp.Send(mail);
                Console.WriteLine("Email Sent Successfully.");
            }
            catch (Exception ex) { 
            
                //Burde skrive ut error melding eller logge den
                Console.WriteLine(ex.ToString());
            }

            return RedirectToAction("KontaktOss");
        
        }
    }
}

ProsjektNosted/Controllers/OmOssController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Prosjekt.Controllers
{
    public class OmOssController : Controller
    {
        // GET: /<controller>/
        public IActionResult index()
        {
            return View();
        }
    }
}

ProsjektNosted/Controllers/OversiktController.cs
using Microsoft.AspNetCore.Mvc;
using Prosjekt.Models.Oversikt;

namespace Prosjekt.Controllers
{
    public class OversiktController : Controller
    {
        private readonly ProsjektContext _context;

        // Constructor for OversiktController
        public OversiktController(ProsjektContext context)
        {
            _context = context;
        }

        // Action metode for å gjengi Oversikt view
        public IActionResult Oversikt()
        {
            // Fetch service ordre fra databasen
            var order = _context.Service_ordre.ToList();


            // Lager en liste forr rå lagre OversiktViewModel objekterr
            List<OversiktViewModel> list = new List<OversiktViewModel>();

            // Convert the fetched data to the view model type
            foreach (var e in order)
            {
                var partsObj = new OversiktViewModel();
                // Henter kundeprodukt informasjon
                var customerPordsduct = _context.Customer_Product.Where(x => x.CustomerID_int == e.CustomerID_int).FirstOrDefault();
                if(customerPordsduct == null)
                {
                    partsObj.WarrantyName = "Ingen garanti";
                    partsObj.Email = "Fant ikke email";
                } else
                {
                    // Henter warranty og kundeinformasjon
                    var warranty = _context.Warranty.Where(x => x.ID_int == customerPordsduct.WarrantyID_int).FirstOrDefault();
                    var customer = _context.Customer.Where(x => x.ID_int == customerPordsduct.CustomerID_int).FirstOrDefault();
                    partsObj.WarrantyName = warranty.WarrantyName_str;
                    partsObj.Email = customer.Email_str;
                }

                // Henter service order service form informasjon
                var Orderform = _context.Service_Order_Service_form.Where(x => x.OrderID_int == e.OrderID_int).FirstOrDefault();
                if (Orderform == null)
                {
                    partsObj.FormID_int = 0;
                    partsObj.BookedServiceWeek_int = 0;
                    partsObj.Repairdescription_str = "Ingen beskrivelse";
                } else
                {
                    // Henter service form informasjon
                    var form = _context.Service_Form.Where(x => x.FormID_int == Orderform.FormID_int).FirstOrDefault();
                    partsObj.FormID_int = form.FormID_int;
                    partsObj.Repairdescription_str = form.Repairdescription_str;
                    partsObj.BookedServiceWeek_int = form.BookedServiceWeek_int;

                }
                // Henter sjekkliste informasjon
                var checklist = _context.Checklist.Where(x => x.DocID_str.Equals(e.SerialNr_str)).FirstOrDefault();

                
                partsObj.OrderID_int = e.OrderID_int;
                partsObj.SerialNr_str = e.SerialNr_str;
                partsObj.Description_From_Customer_str = e.Description_From_Customer_str;

                if(checklist == null)
                {
                    partsObj.DocID_str = "Ingen checkliste";
                } else
                {
                    partsObj.DocID_str = checklist.DocID_str;
                }

                // Legger OversiktViewModel objekt til listen
                list.Add(partsObj);
            }
            // Passerer listen til viewet hvis den inneholder ting
            if (list.Count > 0)
            {
                ViewData["List"] = list;

            }

            return View();
        }
    }
}

ProsjektNosted/Views/Shared/_Footer.cshtml
@using Microsoft.AspNetCore.Identity
@using Prosjekt.Entities;
@using Prosjekt.Services;

@inject SignInManager<EmployeeUser> SignInManager
@inject UserManager<EmployeeUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <footer class="border-top text-white py-0">
        <div class="container">
            <div class="row align-items-center justify-content-between">

                <div class="col-md-4 text-md-left text-center footer-brand mb-3 mb-md-0">
                    <img src="~/Images/Nostedlogo.png" alt="Nøsted sin logo" />
                </div>


                <!-- Navigation -->

                <!-- Social medias -->
                <div class="col-md-4 d-flex justify-content-md-end justify-content-center mt-3 mt-md-0 social-icon">
                    <a href="https://www.facebook.com/nostedand" target="_blank" class="px-2">
                        <img src="/icons/icons8-facebook-48.png" alt="Facebook">
                    </a>
                    <a href="https://www.linkedin.com/company/nosted?originalSubdomain=no" target="_blank" class="px-2">
                        <img src="/icons/icons8-linkedin-48.png" alt="Linkedin">
                    </a>
                    <a href="https://www.instagram.com/nosted_com" target="_blank" class="px-2">
                        <img src="/icons/icons8-instagram-48.png" alt="Instagram">
                    </a>
                    <a href="https://www.youtube.com/channel/UCVj5kmVOZhzOBGA4cKQTQZA?view_as=subscriber" target="_blank" class="px-2">
                        <img src="/icons/icons8-youtube-48.png" alt="Youtube">
                    </a>
                </div>
            </div>
        </div>
    </footer>
}
else
{
    <footer class="border-top text-white py-4">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md-4 text-md-left text-center footer-brand mb-5 mb-md-0">
                    <img src="~/Images/Nostedlogo.png" alt="Nøsted sin logo" />
                </div>

                <!-- Navigation -->
                <div class="col-md-4 text-center">
                    <a asp-controller="Home" asp-action="Privacy" class="text-lighter-white h4 d-block d-md-inline mb-3 mb-md-0 me-md-3">Personvern</a>
                    <a asp-controller="Kontakt" asp-action="KontaktOss" class="text-lighter-white h4 d-block d-md-inline mb-3 mb-md-0 me-md-3">Kontakt oss</a>
                    <a asp-controller="FAQ" asp-action="FAQ" class="text-lighter-white h4 d-block d-md-inline mb-3 mb-md-0">FAQ</a>
                </div>

                <!-- Social medias -->
                <div class="col-md-4 d-flex justify-content-md-end justify-content-center mt-3 mt-md-0 social-icon">
                    <a href="https://www.facebook.com/nostedand" target="_blank" class="px-2">
                        <img src="/icons/icons8-facebook-48.png" alt="Facebook">
                    </a>
                    <a href="https://www.linkedin.com/company/nosted?originalSubdomain=no" target="_blank" class="px-2">
                        <img src="/icons/icons8-linkedin-48.png" alt="Linkedin">
                    </a>
                    <a href="https://www.instagram.com/nosted_com" target="_blank" class="px-2">
                        <img src="/icons/icons8-instagram-48.png" alt="Instagram">
                    </a>
                    <a href="https://www.youtube.com/channel/UCVj5kmVOZhzOBGA4cKQTQZA?view_as=subscriber" target="_blank" class="px-2">
                        <img src="/icons/icons8-youtube-48.png" alt="Youtube">
                    </a>
                </div>
            </div>
        </div>
    </footer>
}

ProsjektNosted/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Prosjekt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bs-stepper/dist/css/bs-stepper.min.css">
    <!-- Link to Bootstrap 5.3.2 CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
<!--dropdown-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
    <!-- Link to Bootstrap 5.3.2 JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"></script>
    <!-- adder rett under link til bootstrap fra den siden jeg fant (ine)-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bs-stepper/dist/js/bs-stepper.min.js"></script>
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/buttons.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Sjekklist.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/serviceordre.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/serviceskjema.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/Oversikt.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/Register.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/css/Logginn.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/css/FAQ.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Arbeidsdokument.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/css/Brukeroversikt-popup.css" asp-append-version="true" />

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark p-3 border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/Nostedlogo.png" alt="Nøsted sin logo" />
                </a>
                 
                        <partial name="_Navbar" />
            </div>
        </nav>
    </header>

    <div class="d-flex flex-column h-100"> <!-- min-vh-100 -->
        <div class="flex-grow-1 ">
            <div id="mainContainer" class="container-fluid flex-fill p-0 h-100">
                <main role="main" class="h-100 w-100">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <partial name="_Footer" />



<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

ProsjektNosted/Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Identity
@using Prosjekt.Entities;
@using Prosjekt.Services;

@inject SignInManager<EmployeeUser> SignInManager
@inject UserManager<EmployeeUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    @if (User.IsInRole("Admin"))
    {
        <li class="nav-item">
            <a id="manage" class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @UserManager.GetUserName(User)!</a>
        </li>
        <input type="checkbox" id="toggle" style="display:none;">
        <label for="toggle" class="nav-link d-flex align-items-center">
            <span class="hamburger">
                <span class="top"></span>
                <span class="middle"></span>
                <span class="bottom"></span>
            </span>
        </label>
        <ul class="menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" asp-controller="Parts" asp-action="Parts">Deler</a></li>
            <li><a class="dropdown-item" asp-controller="Oversikt" asp-action="Oversikt">Oversikt</a></li>
            <li><a class="dropdown-item" asp-controller="Equipment" asp-action="Equipment">Utstyr</a></li>
            <li><a class="dropdown-item" asp-controller="Arbeidsdokument" asp-action="Arbeidsdokument">Arbeidsdokument</a></li>
            <li><a class="dropdown-item" asp-controller="Employees" asp-action="Employees">Brukeroversikt</a></li>
            <li><a class="dropdown-item" id="login" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">Logout</a></li>
        </ul>
        }
    @if (User.IsInRole("Mekanisk") || User.IsInRole("Hydraulisk") || User.IsInRole("Elektro"))
    {
        {
            <li class="nav-item">
                <a id="manage" class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @UserManager.GetUserName(User)!</a>
            </li>
            <input type="checkbox" id="toggle" style="display:none;">
            <label for="toggle" class="nav-link d-flex align-items-center">
                <span class="hamburger">
                    <span class="top"></span>
                    <span class="middle"></span>
                    <span class="bottom"></span>
                </span>
            </label>
            <ul class="menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" asp-controller="Parts" asp-action="Parts">Deler</a></li>
                <li><a class="dropdown-item" asp-controller="Equipment" asp-action="Equipment">Utstyr</a></li>
                <li><a class="dropdown-item" asp-controller="Oversikt" asp-action="Oversikt">Oversikt</a></li>
            <li><a class="dropdown-item" asp-controller="Arbeidsdokument" asp-action="Arbeidsdokument">Arbeidsdokument</a></li>
            <li><a class="dropdown-item" id="login" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">Logout</a></li>
        </ul>
        }
    }
}
else
{
    <input type="checkbox" id="toggle" style="display:none;">
    <label for="toggle" class="nav-link d-flex align-items-center">
        <span class="hamburger">
            <span class="top"></span>
            <span class="middle"></span>
            <span class="bottom"></span>
        </span>
    </label>
    <ul class="menu" aria-labelledby="navbarDropdownMenuLink">
        <li><a class="dropdown-item" asp-controller="Home" asp-action="Privacy">Personvern</a></li>
        <li><a class="dropdown-item" asp-controller="Kontakt" asp-action="KontaktOss">Kontakt oss</a></li>
        <li><a class="dropdown-item" asp-controller="FAQ" asp-action="FAQ">FAQ</a></li>
        <li><a class="dropdown-item" asp-controller="OmOss" asp-action="index">Om Oss</a></li>

        <li><a class="dropdown-item" id="login" asp-area="Identity" asp-page="/Account/Login">Login</a></li>

    </ul>
}